import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import './index.css';
import App from './App';

// Font Awesome setup
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faSignal,
  faCar,
  faExclamationTriangle,
  faClock,
  faDownload,
  faCog,
  faRoute,
  faAmbulance,
  faTrafficLight,
  faChartBar,
  faMapMarkerAlt,
  faEye,
  faCheckCircle,
  faExclamationCircle,
  faArrowUp,
  faArrowDown,
  faChartLine,
  faUsersCog,
  faHistory,
  faSync,
  faFilter,
  faSearch,
  faMapMarker,
  faRoad,
  faLightbulb,
  faBell,
  faSpinner,
  faTachometerAlt,
  faExclamation,
  faInfoCircle,
  faTimesCircle,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faLocationArrow,
  faMapMarkedAlt,
  faCircleNotch,
  faCarCrash,
  faHardHat,
  faCloudRain,
  faCalendarAlt,
  faTimes,
  faCompass,
  faSearchLocation,
  faMapPin,
  faStreetView,
  faDirections,
  faLayerGroup,
  faExpand,
  faCompress,
  faHome,
  faBuilding,
  faIndustry,
  faSchool,
  faHospital,
  faShoppingCart,
  faCrosshairs
} from '@fortawesome/free-solid-svg-icons';

// Add icons to library
library.add(
  faSignal,
  faCar,
  faExclamationTriangle,
  faClock,
  faDownload,
  faCog,
  faRoute,
  faAmbulance,
  faTrafficLight,
  faChartBar,
  faMapMarkerAlt,
  faEye,
  faCheckCircle,
  faExclamationCircle,
  faArrowUp,
  faArrowDown,
  faChartLine,
  faUsersCog,
  faHistory,
  faSync,
  faFilter,
  faSearch,
  faMapMarker,
  faRoad,
  faLightbulb,
  faBell,
  faSpinner,
  faTachometerAlt,
  faExclamation,
  faInfoCircle,
  faTimesCircle,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faLocationArrow,
  faMapMarkedAlt,
  faCircleNotch,
  faCarCrash,
  faHardHat,
  faCloudRain,
  faCalendarAlt,
  faTimes,
  faCompass,
  faSearchLocation,
  faMapPin,
  faStreetView,
  faDirections,
  faLayerGroup,
  faExpand,
  faCompress,
  faHome,
  faBuilding,
  faIndustry,
  faSchool,
  faHospital,
  faShoppingCart,
  faCrosshairs
);

ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById('root')
);